site_name: Custom PyQt Objects

theme: 
  name:
    material

nav:
  - Home: 'index.md'
  - Widgets: 'widgets.md'
  - Core: 'core.md'
  - Gui: 'gui.md'
    
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
            docstring_style: numpy